### ISSUE TITLE
Adjecency Matrix for the Dynamic Models

### ISSUE THREAD

**Issue by falihgoz** [elgazzarr/fMRIGNNs#1]
Hi,

Thanks for sharing your great work. I have a question regarding the adjacency matrix for the dynamic models. Do you use a similar adj matrix for all subjects, or did you use different adj matrices for each subject during dynamic modeling?

Many thanks in advance,

**Comment by elgazzarr** [comment]
Hi, Thanks for your interest.
I use a similar adj matrix for all the subjects. I have experimented with single subject adj. for dynamic models but that never worked for me. only with static models it converged.
